export const MARKET = {
  SOCKET_URL: 'http://localhost:3000/market',
  PRICES_ALL_EVENT: 'prices',
  PRICES_STOCK_EVENT: 'prices:stockMarket',
  PRICES_PRECIOUS_EVENT: 'prices:preciousMetals',
  SYMBOLS_ALL_EVENT: 'symbols',
  SYMBOLS_STOCK_EVENT: 'symbols:stockMarket',
  SYMBOLS_PRECIOUS_EVENT: 'symbols:preciousMetals',
  LABELS_ALL_EVENT: 'symbolsWithLabels',
  LABELS_STOCK_EVENT: 'symbolsWithLabels:stockMarket',
  LABELS_PRECIOUS_EVENT: 'symbolsWithLabels:preciousMetals',
  MAX_RECONNECT_ATTEMPTS: 5,
  MAX_RECONNECT_DELAY_MS: 10000,
  RECONNECT_BASE_DELAY_MS: 1000,
} as const;